services:
    app:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        depends_on:
            - postgres
        ports:
            - "9090:9090"
        volumes:
            - ./:/usr/src/app/
            - /usr/src/app/node_modules
    postgres:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
        ports:
            - "5433:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data 
    redis:
        image: redis:latest
        restart: always
        ports:
        - "6379:6379"
        volumes:
        - cache:/data
volumes:
    pgdata:
        driver: local
    cache:
        driver: local
